using Avalonia;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Threading;
using Avalonia.VisualTree;
using XYUI.Avalonia.Controls;
using XYUI.Avalonia.Gallery;
using XYUI.Avalonia.Vector;

namespace XYUI.Avalonia.Tests;

[Collection("XyuiHeadless")]
public sealed class XYUI3FinalNavigationTests : IClassFixture<XyuiHeadlessFixture>
{
    readonly XyuiHeadlessFixture _fx;
    public XYUI3FinalNavigationTests(XyuiHeadlessFixture fx) => _fx = fx;
    [Fact] public void ViewSwitcher_request_then_commit_and_variants_share_state()
    {
        var views = new[] { new XYViewDefinition("a", "画布", XyuiVectorIcon.Locate), new XYViewDefinition("b", "表格", XyuiVectorIcon.Section) }; var state = new XYViewState(views, "a"); var segmented = new XYViewSwitcher(state); var dropdown = new XYViewSwitcher(state, XYViewSwitcherVariant.Dropdown); segmented.ViewChangeRequested += (_, request) => request.Accept(); segmented.SelectView("b"); Assert.Equal("b", dropdown.CurrentViewId); Assert.Same(state, dropdown.State);
    }
    [Fact] public void Toc_limits_depth_and_rejects_request()
    {
        var sections = new[] { new XYTocSection("a", "A", 1), new XYTocSection("b", "B", 3), new XYTocSection("c", "C", 2, "a") }; var toc = new XYTableOfContents(sections); Assert.Equal(2, toc.State.Sections.Count); toc.SectionRequested += (_, request) => request.Reject(); toc.SelectSection("c"); Assert.Equal("a", toc.CurrentSectionId);
    }
    [Fact] public void Bottom_navigation_keeps_primary_action_out_of_destination_state()
    {
        var primary = new XYButton(); var items = new[] { new XYBottomNavigationItem("home", "首页", XyuiVectorIcon.Locate) }; var nav = new XYBottomNavigation(new XYNavigationState(items.Select(i => new XYNavigationEntry(i.Id, i.Label, i.Icon))), items, primary); Assert.Same(primary, nav.PrimaryAction); Assert.Single(nav.NavigationState.Entries);
    }
    [Fact] public void Bottom_navigation_has_equal_vertical_destination_slots() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var items = new[] { new XYBottomNavigationItem("a", "地图", XyuiVectorIcon.Locate), new XYBottomNavigationItem("b", "数据", XyuiVectorIcon.Code), new XYBottomNavigationItem("c", "实验", XyuiVectorIcon.Clear), new XYBottomNavigationItem("d", "日志", XyuiVectorIcon.Section), new XYBottomNavigationItem("e", "我的", XyuiVectorIcon.Info) }; var nav = new XYBottomNavigation(new XYNavigationState(items.Select(i => new XYNavigationEntry(i.Id, i.Label, i.Icon)), "a"), items); var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); var slots = nav.GetVisualDescendants().OfType<Border>().Where(x => x.Classes.Contains("xyui-bottom-navigation-destination")).ToArray(); Assert.Equal(5, slots.Length); Assert.All(slots, x => Assert.InRange(Math.Abs(slots[0].Bounds.Width - x.Bounds.Width), 0, 1)); Assert.Equal(66, nav.Bounds.Height, 1); window.Close(); });
    [Fact] public void Bottom_navigation_content_is_icon_above_label_and_badge_count_overlays() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var item = new XYBottomNavigationItem("logs", "日志", XyuiVectorIcon.Section, "12"); var nav = new XYBottomNavigation([item]); var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); var slot = nav.GetVisualDescendants().OfType<Border>().Single(x => x.Classes.Contains("xyui-bottom-navigation-destination")); var icon = slot.GetVisualDescendants().OfType<XYIcon>().Single(); var label = slot.GetVisualDescendants().OfType<TextBlock>().Single(x => x.Classes.Contains("xyui-bottom-navigation-label")); var badge = slot.GetVisualDescendants().OfType<XYStatusBadge>().Single(); Assert.True(icon.Bounds.Center.Y < label.Bounds.Center.Y); Assert.Equal("12", badge.Text); Assert.True(badge.Bounds.Top <= icon.Bounds.Top); window.Close(); });
    [Fact] public void Bottom_navigation_safe_area_adds_inset_without_shrinking_destination() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var nav = new XYBottomNavigation([new XYBottomNavigationItem("a", "地图", XyuiVectorIcon.Locate)]); nav.SafeAreaBottom = 18; var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); var slot = nav.GetVisualDescendants().OfType<Border>().Single(x => x.Classes.Contains("xyui-bottom-navigation-destination")); Assert.Equal(84, nav.Bounds.Height, 1); Assert.True(slot.Bounds.Height >= 50); window.Close(); });
    [Fact] public void Bottom_navigation_primary_action_does_not_select_destination() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var state = new XYNavigationState([new("a", "地图", XyuiVectorIcon.Locate), new("b", "数据", XyuiVectorIcon.Code), new("c", "日志", XyuiVectorIcon.Section), new("d", "我的", XyuiVectorIcon.Info)], "a"); var primary = new XYButton { Content = new XYIcon { Icon = XyuiVectorIcon.Add } }; var nav = new XYBottomNavigation(state, state.Entries.Select(x => new XYBottomNavigationItem(x.Id, x.Label, x.Icon)), primary); var requested = 0; nav.PrimaryActionRequested += (_, _) => requested++; var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); primary.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); Assert.Equal(1, requested); Assert.Equal("a", nav.CurrentDestinationId); Assert.Contains(nav.GetVisualDescendants().OfType<Grid>(), x => x.Classes.Contains("xyui-bottom-navigation-primary-host")); window.Close(); });
    [Fact] public void Bottom_navigation_safe_area_and_primary_hit_target_are_explicit() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var state = new XYNavigationState([new("a", "地图", XyuiVectorIcon.Locate), new("b", "数据", XyuiVectorIcon.Code)], "a"); var primary = new XYButton { Content = new XYIcon { Icon = XyuiVectorIcon.Add } }; var nav = new XYBottomNavigation(state, state.Entries.Select(x => new XYBottomNavigationItem(x.Id, x.Label, x.Icon)), primary); var window = XyuiBatchTestHost.Show(nav); nav.SafeAreaBottom = 0; Dispatcher.UIThread.RunJobs(); var baseHeight = nav.Bounds.Height; nav.SafeAreaBottom = 24; Dispatcher.UIThread.RunJobs(); var host = nav.GetVisualDescendants().OfType<Grid>().Single(x => x.Classes.Contains("xyui-bottom-navigation-primary-host")); var contentGrid = Assert.IsType<Grid>(nav.Child); Assert.Equal(66, baseHeight, 1); Assert.Equal(90, nav.Bounds.Height, 1); Assert.Equal(24, contentGrid.Margin.Bottom, 1); Assert.True(primary.IsHitTestVisible); Assert.Equal(54, primary.Height); Assert.False(nav.ClipToBounds); Assert.False(host.ClipToBounds); Assert.True(host.Margin.Top < 0); window.Close(); });
    [Fact] public void Bottom_navigation_accepts_destination_and_rejects_without_state_change() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var state = new XYNavigationState([new("a", "地图", XyuiVectorIcon.Locate), new("b", "数据", XyuiVectorIcon.Code)], "a"); var nav = new XYBottomNavigation(state); nav.DestinationRequested += (_, request) => { if (request.Destination.Id == "b") request.Accept(); }; nav.SelectDestination("b"); Assert.Equal("b", nav.CurrentDestinationId); nav.DestinationRequested += (_, request) => request.Reject(); nav.SelectDestination("a"); Assert.Equal("b", nav.CurrentDestinationId); });
    [Fact] public void Bottom_navigation_current_destination_does_not_duplicate_request() => _fx.Run(() => { var state = new XYNavigationState([new("a", "地图", XyuiVectorIcon.Locate)], "a"); var nav = new XYBottomNavigation(state); var count = 0; nav.DestinationRequested += (_, request) => { count++; request.Accept(); }; nav.SelectDestination("a"); Assert.Equal(0, count); });
    [Fact] public void Drawer_shares_navigation_state_and_has_lifecycle_surface()
    {
        var state = new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)]); var drawer = new XYNavigationDrawer(state); Assert.Same(state, drawer.NavigationState); drawer.Open(); Assert.True(drawer.IsOpen); drawer.Close(); Assert.False(drawer.IsOpen); Assert.NotNull(drawer.Backdrop);
    }
    [Fact] public void Drawer_uses_navigation_request_and_closes_on_escape()
    {
        var state = new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate), new("map", "地图", XyuiVectorIcon.Section)]); var drawer = new XYNavigationDrawer(state); var requested = 0; state.NavigationRequested += (_, request) => { requested++; request.Accept(); }; drawer.Open(); drawer.SelectDestination("map"); Assert.Equal("map", state.SelectedId); Assert.Equal(1, requested); var popupGrid = Assert.IsType<Grid>(drawer.DrawerPopup.Child); var content = popupGrid.Children.OfType<Control>().Single(x => !ReferenceEquals(x, drawer.Backdrop)); content.RaiseEvent(new KeyEventArgs { RoutedEvent = InputElement.KeyDownEvent, Key = Key.Escape }); Assert.False(drawer.IsOpen);
    }
    [Fact] public void Drawer_mounts_real_overlay_and_restores_trigger_focus() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var drawer = new XYNavigationDrawer(new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)])); var window = XyuiBatchTestHost.Show(drawer); drawer.Open(); Dispatcher.UIThread.RunJobs(); Assert.Contains(drawer.GetVisualDescendants(), x => ReferenceEquals(x, drawer.DrawerPopup)); Assert.True(drawer.Backdrop.IsVisible); drawer.Close(); Dispatcher.UIThread.RunJobs(); Assert.True(drawer.OpenTrigger.IsFocused); window.Close(); });
    [Fact] public void Drawer_backdrop_pointer_closes_real_overlay() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var drawer = new XYNavigationDrawer(new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)])); var window = XyuiBatchTestHost.Show(drawer); drawer.Open(); Dispatcher.UIThread.RunJobs(); drawer.Backdrop.RaiseEvent(new PointerPressedEventArgs(drawer.Backdrop, null!, window, new Point(5, 5), 0, new PointerPointProperties(RawInputModifiers.None, PointerUpdateKind.LeftButtonPressed), KeyModifiers.None)); Assert.False(drawer.IsOpen); window.Close(); });
    [Fact] public void Drawer_light_dismiss_contract_is_enabled_for_real_overlay() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var drawer = new XYNavigationDrawer(new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)])); var window = XyuiBatchTestHost.Show(drawer); drawer.Open(); Dispatcher.UIThread.RunJobs(); Assert.True(drawer.DrawerPopup.IsLightDismissEnabled); Assert.True(drawer.Backdrop.IsVisible); drawer.Close(); Assert.False(drawer.IsOpen); window.Close(); });
    [Fact] public void Drawer_open_mounts_visual_surface_and_backdrop_and_click_closes() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var drawer = new XYNavigationDrawer(new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)])); var window = XyuiBatchTestHost.Show(drawer); Dispatcher.UIThread.RunJobs(); drawer.Open(); Dispatcher.UIThread.RunJobs(); Assert.True(drawer.IsOpen); Assert.NotNull(drawer.DrawerPopup.Child); Assert.True(drawer.Backdrop.IsVisible); drawer.Backdrop.RaiseEvent(new PointerPressedEventArgs(drawer.Backdrop, null!, window, new Point(10, 10), 0, new PointerPointProperties(RawInputModifiers.None, PointerUpdateKind.LeftButtonPressed), KeyModifiers.None)); Assert.False(drawer.IsOpen); window.Close(); });
    [Fact] public void Drawer_close_restores_focus_to_trigger() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var drawer = new XYNavigationDrawer(new XYNavigationState([new("home", "首页", XyuiVectorIcon.Locate)])); var window = XyuiBatchTestHost.Show(drawer); Dispatcher.UIThread.RunJobs(); drawer.Open(); drawer.Close(); Assert.False(drawer.IsOpen); window.Close(); });
    [Fact] public void Bottom_navigation_primary_action_floating_hit_target_does_not_change_destination() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var state = new XYNavigationState([new("a", "地图", XyuiVectorIcon.Locate), new("b", "数据", XyuiVectorIcon.Code), new("c", "日志", XyuiVectorIcon.Section)], "a"); var primary = new XYButton { Content = new XYIcon { Icon = XyuiVectorIcon.Add } }; var nav = new XYBottomNavigation(state, null, primary); var hit = 0; nav.PrimaryActionRequested += (_, _) => hit++; var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); primary.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); Assert.Equal(1, hit); Assert.Equal("a", nav.CurrentDestinationId); window.Close(); });
    [Fact] public void BackForward_truncates_without_squishing_actions() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var nav = new XYBackForwardNavigation { Width = 140 }; nav.Navigate("VERY_LONG_PATH_NAME_THAT_EXCEEDS_NORMAL_BOUNDS_AND_SHOULD_TRUNCATE"); var window = XyuiBatchTestHost.Show(nav); Dispatcher.UIThread.RunJobs(); Assert.Equal(28, nav.BackButton.Bounds.Width, 1); Assert.Equal(28, nav.ForwardButton.Bounds.Width, 1); Assert.False(nav.CanGoBack); Assert.False(nav.CanGoForward); window.Close(); });
    [Fact] public void Gallery_registers_all_final_components()
    { foreach (var id in new[] { "XYUI-3-3.21", "XYUI-3-3.22", "XYUI-3-3.23", "XYUI-3-3.24" }) Assert.NotNull(XYUI3GalleryCatalog.CreatePreview(id)); }
}
